### PR TITLE
add option to select all procedures

### PR DESCRIPTION
**Pull request by ukos-git**
load objects from all procedures by selecting constant CB_selectALL.

not fully tested, but working

Close #35.

### CODE REVIEW

**Comment by ukos-git** [comment]
panel display is optimized for igor8. Looks a bit unaligned in igor6.

screenshot from 2019-01-12 19-56-59
screenshot from 2019-01-12 19-57-21

**Comment by ukos-git** [comment]
@t-b Working and ready for review (but in early stage and vastly untetested!)

**Comment by ukos-git** [comment]
found an error: it removed panel position/width/last selected item at package prefs

**Comment by ukos-git** [comment]
found error: search is not working within the complete procedure list

**Comment by t-b** [comment]
@ukos-git Review:

Functionality:
- [ ] Double clicking a function from the list with `all` selected does not work. Reason seems to be that `showCode` does not know how to handle `<ALL>`.
- [ ] Change menu entry to `<ALL>` just as we use for Namespace instead of `<ALL Procedures`. Or?
- [ ] I get a "package prefs has wrong size on disc" error on first load. You changed `CodeBrowserPrefs` in a way that the new struct has a different size than the old struct. And the reason is I think that you moved 40 entries from reservered (which is a 4 byte unsigned integer) to 40 chars (which are one byte each). So the size changed.

Code wise:
- Moving to panel macro is very nice!
- `filterSet` should have a better name, no unused variables and no unused cases.

**Comment by ukos-git** [comment]
did a complete rework.

**Pull request merged**
